channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.1.2
- pip:
  - mlflow==2.22.0
  - category-encoders==2.7.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - scikit-learn==1.4.2
  - scipy==1.11.4
  - xgboost==3.0.0
name: mlflow-env
